### ISSUE TITLE
Good project but did you heard about REX-Diagnostics?

### ISSUE THREAD

**Issue by friuns2** [marijnz/unity-shell#12]
There is more mature project that does same thing or is there any difference?

https://github.com/thorgeirk11/REX-Diagnostics

**Comment by MostHated** [comment]
The more the marrier.

**Comment by marijnz** [comment]
I agree with @MostHated :) 

I made this because I only saw one other version of this (UniShell), on which I could make a version which better UX. People call these Editor tools differently which makes it hard to know what's actually out there. Things made for Unity are also kinda fragmented (Asset Store, GitHub, StackOverflow, personal/company websites).

I didn't know of REX-Diagnostics but it looks well done! Thanks for sharing. It would be interesting to see how some of the concepts in there could be implemented in unity-shell. However I think it's also important to keep things simple.

On the difference: I think choosing one or the other is first of all a UI preference. I'd prefer to have it "terminal style" instead of a single line input field, as do (unexpectedly) many people besides me apparently. However REX-Diagnostics is definitely more mature in a sense of amount of features and it looks user friendly and the features are nicely integrated, so as I said, let's see what could be implemented in unity-shell! :)

**Comment by marijnz** [comment]
Also: I like the output box and I like some of the color coding, it looks intuitive. I don't like the UI in general so much, it's a lot of stuff on the screen which are equally asking for your attention (but OK, they can be folded). What do you guys think?

**Comment by friuns2** [comment]
Only thing i missing from there is multiline editing, you can paste code snipets but they must be one liner seperated with ;
Other thing is, you cant access to internal or private variables if you know @marijnz how to bypass that? only by reflection but you need write a lot more code in shell

if you gona make code highlighting would be cool if you could integrate with this project it have source code included https://assetstore.unity.com/packages/tools/visual-scripting/script-inspector-3-3535

**Comment by marijnz** [comment]
Hi, it would be possible to make a command that lists all variables, or add a button or add tabs as in a webbrowser or something. Lots of ways to do it. I don't see the need for it so much. But you can contribute! :) 
As for SI3. I worked with it before to hack stuff together, and it's a very big codebase with huge source files. Integrating it would multiply the current project complexity by (a very un-scientific estimation) 10 times, if not more. I don't think that's a viable way to go. But feel free to experiment and share your experience!
